### ISSUE TITLE
 Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.

### ISSUE THREAD

**Issue by chris122380** [joshuawolfsohn/Private-DNS-Quick-Tile#16]
Unable to run the ADB command on Oxygen OS 13. I get the following errors.

```
OnePlus9Pro:/ $ pm grant com.jpwolfso.privdnsqt android.permission.WRITE_SECURE_SETTINGS

Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2263)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2291)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1364)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1346)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:553)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:597)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2591)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:302)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6365)
        at android.os.Binder.shellCommand(Binder.java:1073)
        at android.os.Binder.onTransact(Binder.java:901)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6349)
        at android.os.Binder.execTransactInternal(Binder.java:1331)
        at android.os.Binder.execTransact(Binder.java:1268)
```

**Comment by Phantomial69** [comment]
> Unable to run the ADB command on Oxygen OS 13. I get the following errors.
> 
> ```
> OnePlus9Pro:/ $ pm grant com.jpwolfso.privdnsqt android.permission.WRITE_SECURE_SETTINGS
> 
> Exception occurred while executing 'grant':
> java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
>         at android.app.ContextImpl.enforce(ContextImpl.java:2263)
>         at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2291)
>         at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1364)
>         at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1346)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:553)
>         at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:597)
>         at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2591)
>         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:302)
>         at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
>         at android.os.ShellCommand.exec(ShellCommand.java:38)
>         at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6365)
>         at android.os.Binder.shellCommand(Binder.java:1073)
>         at android.os.Binder.onTransact(Binder.java:901)
>         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
>         at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6349)
>         at android.os.Binder.execTransactInternal(Binder.java:1331)
>         at android.os.Binder.execTransact(Binder.java:1268)
> ```

Same thing happened to me too. (Realme UI Android 11)

**Comment by Phantomial69** [comment]
> Unable to run the ADB command on Oxygen OS 13. I get the following errors.
> 
> ```
> OnePlus9Pro:/ $ pm grant com.jpwolfso.privdnsqt android.permission.WRITE_SECURE_SETTINGS
> 
> Exception occurred while executing 'grant':
> java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
>         at android.app.ContextImpl.enforce(ContextImpl.java:2263)
>         at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2291)
>         at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1364)
>         at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1346)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:553)
>         at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:597)
>         at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2591)
>         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:302)
>         at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
>         at android.os.ShellCommand.exec(ShellCommand.java:38)
>         at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6365)
>         at android.os.Binder.shellCommand(Binder.java:1073)
>         at android.os.Binder.onTransact(Binder.java:901)
>         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
>         at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6349)
>         at android.os.Binder.execTransactInternal(Binder.java:1331)
>         at android.os.Binder.execTransact(Binder.java:1268)
> ```

https://stackoverflow.com/questions/52079343/how-can-i-use-adb-to-grant-permission-without-root

In Developer Options, scroll down until u find Disable Permission Monitoring (I noticed that they change it to USB debugging (Security setting)and it require a sim)
